// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Action struct {
	ID                int64         `json:"id"`
	Name              string        `json:"name"`
	IDActions         sql.NullInt32 `json:"idActions"`
	Isin              string        `json:"isin"`
	Wkn               string        `json:"wkn"`
	CurrentValue      string        `json:"currentValue"`
	Bid               string        `json:"bid"`
	Ask               string        `json:"ask"`
	Spread            string        `json:"spread"`
	TimeOfLastRefresh time.Time     `json:"timeOfLastRefresh"`
	ChangePercentage  string        `json:"changePercentage"`
	ChangeAbsolute    string        `json:"changeAbsolute"`
	Peak24h           string        `json:"peak24h"`
	Low24h            string        `json:"low24h"`
	Peak7d            string        `json:"peak7d"`
	Low7d             string        `json:"low7d"`
	Peak30d           string        `json:"peak30d"`
	Low30d            string        `json:"low30d"`
	CreatedAt         time.Time     `json:"createdAt"`
}

type Buy struct {
	ID           int64     `json:"id"`
	ActionIDBuy  int64     `json:"actionIDBuy"`
	ProfileID    int64     `json:"profileID"`
	NumberStocks int32     `json:"numberStocks"`
	Limit        string    `json:"limit"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Player struct {
	IDPlayer          int64          `json:"idPlayer"`
	Username          sql.NullString `json:"username"`
	HashedPassword    string         `json:"hashedPassword"`
	FullName          string         `json:"fullName"`
	Cash              string         `json:"cash"`
	Email             string         `json:"email"`
	PasswordChangedAt time.Time      `json:"passwordChangedAt"`
	CreatedAt         time.Time      `json:"createdAt"`
}

type Portfolio struct {
	ID        int64     `json:"id"`
	PlayerID  int64     `json:"playerID"`
	CreatedAt time.Time `json:"createdAt"`
}

type PortfolioAction struct {
	ID            int32     `json:"id"`
	PortfolioID   int64     `json:"portfolioID"`
	ActionID      int64     `json:"actionID"`
	PlayerID      int64     `json:"playerID"`
	Quantity      int32     `json:"quantity"`
	PurchasePrice string    `json:"purchasePrice"`
	CreatedAt     time.Time `json:"createdAt"`
}
