// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Action struct {
	ID                int64         `json:"id"`
	Name              string        `json:"name"`
	IdActions         sql.NullInt32 `json:"idActions"`
	ISIN              string        `json:"ISIN"`
	WKN               string        `json:"WKN"`
	CurrentValue      interface{}   `json:"currentValue"`
	BID               interface{}   `json:"BID"`
	ASK               interface{}   `json:"ASK"`
	Spread            interface{}   `json:"spread"`
	TimeOfLastRefresh interface{}   `json:"timeOfLastRefresh"`
	ChangePercentage  interface{}   `json:"changePercentage"`
	ChangeAbsolute    interface{}   `json:"changeAbsolute"`
	Peak24h           interface{}   `json:"peak24h"`
	Low24h            interface{}   `json:"low24h"`
	Peak7d            interface{}   `json:"peak7d"`
	Low7d             interface{}   `json:"low7d"`
	Peak30d           interface{}   `json:"peak30d"`
	Low30d            interface{}   `json:"low30d"`
	CreatedAt         time.Time     `json:"createdAt"`
}

type Buy struct {
	ID           int64       `json:"id"`
	ActionIdBuy  int64       `json:"actionIdBuy"`
	ProfileId    int64       `json:"profileId"`
	NumberStocks int32       `json:"numberStocks"`
	Limit        interface{} `json:"limit"`
	CreatedAt    time.Time   `json:"createdAt"`
}

type Player struct {
	ID                int64          `json:"id"`
	Username          sql.NullString `json:"username"`
	HashedPassword    string         `json:"hashedPassword"`
	FullName          string         `json:"fullName"`
	Cash              interface{}    `json:"cash"`
	Email             string         `json:"email"`
	PasswordChangedAt time.Time      `json:"passwordChangedAt"`
	CreatedAt         time.Time      `json:"createdAt"`
}

type Portfolio struct {
	ID        int64     `json:"id"`
	PlayerId  int64     `json:"playerId"`
	CreatedAt time.Time `json:"createdAt"`
}

type PortfolioAction struct {
	ID            int32       `json:"id"`
	PortfolioId   int64       `json:"portfolioId"`
	ActionId      int64       `json:"actionId"`
	PlayerId      int64       `json:"playerId"`
	Quantity      int32       `json:"quantity"`
	PurchasePrice interface{} `json:"purchasePrice"`
	CreatedAt     time.Time   `json:"createdAt"`
}
