// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountPlayers(ctx context.Context) (int64, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Player, error)
	DeletePlayer(ctx context.Context, id int64) error
	GetPlayerByEmail(ctx context.Context, email string) (Player, error)
	GetPlayerById(ctx context.Context, id int64) (Player, error)
	GetPlayerByUsername(ctx context.Context, username sql.NullString) (Player, error)
	ListPlayers(ctx context.Context, arg ListPlayersParams) ([]Player, error)
	RankPlayers(ctx context.Context, arg RankPlayersParams) ([]Player, error)
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
}

var _ Querier = (*Queries)(nil)
